version: '2'
services:
  vulnerable_node:
    container_name: [TOCHANGEWEB]
    restart: always
    build: .
    ports:
      - "3000:3000"
#    links:
#      - postgres_db:postgres_db
    depends_on:
      - postgres_db

  postgres_db:
    container_name: [TOCHANGEDB]
    restart: always
    build: ./services/postgresql
    ports:
      - "5432:5432"
